# Generated by Django 4.2.7 on 2023-12-04 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlevel', '0003_alter_bottomlevel_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomlevel',
            name='task_created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 10, 19, 52, 515546)),
        ),
    ]
