# Generated by Django 5.0.2 on 2024-02-14 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlevel', '0004_alter_bottomlevel_task_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='bottomlevel',
            name='task_created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 16, 40, 52, 241212)),
        ),
    ]
