# Generated by Django 5.0.2 on 2024-02-14 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlevel', '0008_alter_bottomlevel_task_created_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usertbl',
        ),
        migrations.AlterField(
            model_name='bottomlevel',
            name='task_created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 15, 11, 0, 155542)),
        ),
    ]
